name: Build Dev Container
on:
  push:
    paths:
      - '.devcontainer/*'
      - 'requirements.txt'
jobs:
  build_devcontainer:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.IMAGE_REGISTRY_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/animlbook/animl-devcontainer
          cacheFrom: ghcr.io/animlbook/animl-devcontainer
          push: always